services:
  postgres:
    image: postgres:16-alpine
    container_name: nextjs-tailwind-daisyui-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: nextjs_tailwind_daisyui
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
